language: ruby
rvm: 2.4
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - build

before_install:
  - mv ./src/assets/css/main.css ./src/assets/css/$TRAVIS_COMMIT.css
  - mv ./src/assets/js/main.js ./src/assets/js/$TRAVIS_COMMIT.js
  - sed -i "s/main.css/$TRAVIS_COMMIT.css/" ./src/_includes/meta.html
  - sed -i "s/main.js/$TRAVIS_COMMIT.js/" ./src/_includes/footer.html

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "c.a.hooft@gmail.com"
  - git clone --quiet --depth=50 --branch=master https://$GITHUB_API_KEY@github.com/cahooft/cahooft.github.io.git ../master > /dev/null 2>&1
  - rsync -vrth --delete --exclude '.git*' ./html/ ../master/
  - cd ../master
  - git add -A .
  - git commit -am "Automated Build ($TRAVIS_COMMIT)"
  - git push -fq origin master > /dev/null 2>&1
