language: ruby
rvm: 2.5
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

branches:
  only:
    - build

before_script:
  - mv ./src/css/style.css ./src/css/$TRAVIS_COMMIT.css
  - mv ./src/js/script.js ./src/js/$TRAVIS_COMMIT.js
  - sed -i "s/style.css/$TRAVIS_COMMIT.css/" ./src/index.html
  - sed -i "s/script.js/$TRAVIS_COMMIT.js/" ./src/index.html

after_success:
  - git config --global user.name "Automated Build"
  - git config --global user.email "c.a.hooft@gmail.com"
  - git clone --quiet --depth=50 --branch=master https://$GITHUB_API_KEY@github.com/cahooft/cahooft.github.io.git ../master > /dev/null 2>&1
  - rsync -vrth --delete --exclude '.git*' ./html/ ../master/
  - cd ../master
  - git add -A .
  - git commit -am "Automated Build ($TRAVIS_COMMIT)"
  - git push -fq origin master > /dev/null 2>&1
